is_apple_silicon = RUBY_PLATFORM.match?(/arm64|aarch64/)

Vagrant.configure("2") do |config|
  config.vm.define "node1" do |node1|
    node1.vm.hostname = "ubuntu-srv"
    node1.vm.box = "bento/ubuntu-20.04"
    node1.vm.network "private_network", ip: "192.168.56.10"
    node1.vm.provider "vmware_desktop" do |v|
      v.memory = 2048
      v.cpus = 2
      if is_apple_silicon
        v.vmx["ethernet0.virtualdev"] = "vmxnet3"
        v.vmx["ethernet1.virtualdev"] = "vmxnet3"
      end
    end
  end

  config.vm.define "node2" do |node2|
    node2.vm.hostname = "rocky-srv"
    node2.vm.box = "bento/rockylinux-9"
    node2.vm.network "private_network", ip: "192.168.56.11"
    node2.vm.provider "vmware_desktop" do |v|
      v.memory = 2048
      v.cpus = 2
      if is_apple_silicon
        v.vmx["ethernet0.virtualdev"] = "vmxnet3"
        v.vmx["ethernet1.virtualdev"] = "vmxnet3"
      end
    end
  end
end
