Vagrant.configure("2") do |config|
  config.vm.define "node1" do |node1|
    node1.vm.box = "ubuntu/focal64"
    node1.vm.hostname = "ubuntu-srv"
    node1.vm.network "private_network", ip: "192.168.56.10"
    node1.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
      vb.gui = true
    end
  end

  config.vm.define "node2" do |node2|
    node2.vm.box = "bento/rockylinux-9"
    node2.vm.hostname = "rocky-srv"
    node2.vm.network "private_network", ip: "192.168.56.11"
    node2.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
    end
  end
end
